export const PLACE_TYPES_FETCHED = 'PLACE_TYPES_FETCHED'
export const PLACE_TYPE_FETCHED = 'PLACE_TYPE_FETCHED'
export const PLACE_TYPE_CREATED = 'PLACE_TYPE_CREATED'
export const PLACE_TYPE_UPDATED = 'PLACE_TYPE_UPDATED'

export default {
  PLACE_TYPES_FETCHED,
  PLACE_TYPE_FETCHED,
  PLACE_TYPE_CREATED,
  PLACE_TYPE_UPDATED
}
