export const PLACE_CATEGORIES_FETCHED = 'PLACE_CATEGORIES_FETCHED'
export const ALL_PLACE_CATEGORY_FETCHED = 'ALL_PLACE_CATEGORY_FETCHED'
export const PLACE_CATEGORY_CREATED = 'PLACE_CATEGORY_CREATED'
export const PLACE_CATEGORY_UPDATED = 'PLACE_CATEGORY_UPDATED'

export default {
  PLACE_CATEGORIES_FETCHED,
  ALL_PLACE_CATEGORY_FETCHED,
  PLACE_CATEGORY_CREATED,
  PLACE_CATEGORY_UPDATED
}
