export const PICTURES_FETCHED = 'PICTURES_FETCHED'
export const PICTURE_CREATED = 'PICTURE_CREATED'
export const PICTURE_DELETED = 'PICTURE_DELETED'
// export const PLACE_TYPE_UPDATED = 'PLACE_TYPE_UPDATED'

export default {
  PICTURES_FETCHED,
  PICTURE_CREATED,
  PICTURE_DELETED
  // PLACE_TYPE_CREATED,
  // PLACE_TYPE_UPDATED
}
