export const LOCATIONS_FETCHED = 'LOCATIONS_FETCHED'
export const LOCATION_FETCHED = 'LOCATION_FETCHED'
export const LOCATION_CREATED = 'LOCATION_CREATED'
export const LOCATION_UPDATED = 'LOCATION_UPDATED'

export default {
  LOCATIONS_FETCHED,
  LOCATION_FETCHED,
  LOCATION_CREATED,
  LOCATION_UPDATED
}
